version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: local-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-net

  redis:
    image: redis:7
    container_name: local-redis
    restart: unless-stopped
    ports:
      - "6378:6379"
    networks:
      - backend-net

  spring:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: spring-app
    depends_on:
      - mysql
      - redis
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: local
    networks:
      - backend-net

volumes:
  mysql-data:

networks:
  backend-net:
    driver: bridge
