version: '3.8'

services:
  redis:
    image: redis:7
    container_name: prod-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend-net

  nginx:
    image: nginx:latest
    container_name: prod-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - backend
    networks:
      - backend-net

  backend:
    image: foureach/ctrlu-backend:latest
    container_name: prod-spring-app
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      PROD_DB_URL: ${PROD_DB_URL}
      PROD_DB_USERNAME: ${PROD_DB_USERNAME}
      PROD_DB_PASSWORD: ${PROD_DB_PASSWORD}
    networks:
      - backend-net

  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: >
      sh -c "while true; do
        certbot renew --webroot -w /var/lib/letsencrypt --quiet &&
        echo '✔ Renewed! Reloading nginx...' &&
        docker exec prod-nginx nginx -s reload;
        sleep 12h;
      done"
    networks:
      - backend-net
    depends_on:
      - nginx

networks:
  backend-net:
    driver: bridge
