spring:
  profiles:
    group:
      "local": "localDB, prodPort"
      "prod": "prodDB, prodPort"
    active: "local"
  jackson:
    time-zone: Asia/Seoul

---

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secret: ${JWT_SECRET_KEY}

---

spring:
  config:
    activate:
      on-profile: "localDB"
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: redis
      port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    port: 465
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_APP_PASSWORD}
    host: ${EMAIL_HOST}
    request-uri: ${EMAIL_REQUEST_URI}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true
            trust: ${EMAIL_HOST}
        transport:
          protocol: smtp
        debug: true

---

spring:
  config:
    activate:
      on-profile: "prodDB"
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: redis
      port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    port: 465
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_APP_PASSWORD}
    host: ${EMAIL_HOST}
    request-uri: ${EMAIL_REQUEST_URI}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true
            trust: ${EMAIL_HOST}
        transport:
          protocol: smtp
        debug: true

---

spring:
  config:
    activate:
      on-profile: "prodPort"

server:
  port: 9000
