spring:
  profiles:
    group:
      "local": "localDB, prodPort"
      "prod": "prodDB, prodPort"
    active: "local"
  jackson:
    time-zone: Asia/Seoul

---
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

---

spring:
  config:
    activate:
      on-profile: "localDB"
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: redis
      port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

---

spring:
  config:
    activate:
      on-profile: "prodDB"
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

---

spring:
  config:
    activate:
      on-profile: "prodPort"

server:
  port: 9000
