spring:
  profiles:
    group:
      "local": "localDB, prodPort"
      "prod": "prodDB, prodPort"
    active: "local"
  jackson:
    time-zone: Asia/Seoul

---

spring:
  config:
    activate:
      on-profile: "localDB"
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: redis
      port: 6379

---

spring:
  config:
    activate:
      on-profile: "prodDB"
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

---

spring:
  config:
    activate:
      on-profile: "prodPort"

server:
  port: 9000
