name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build and push Docker image
        run: |
          docker build -t foureach/ctrlu-backend:latest ./
          docker push foureach/ctrlu-backend:latest

      - name: SSH and deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ ! -d "/home/ubuntu/ctrlu_backend/.git" ]; then
              git clone https://github.com/four-each/CtrlU_Backend.git /home/ubuntu/ctrlu_backend
            else
              cd /home/ubuntu/ctrlu_backend
              git pull origin dev
            fi
            
            echo "${{ secrets.ENV_PROD }}" > /home/ubuntu/ctrlu_backend/.env.prod
            export $(cat /home/ubuntu/ctrlu_backend/.env.prod | xargs)
            
            cd /home/ubuntu/ctrlu_backend
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d
